import Head from "next/head";

export default function Home({}) {
  return (
    <div className="h-full w-full mx-auto">
      <Head>
        <title>Notion Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen bg-gradient-to-r from-cyan-500 to-blue-500 relative">
        <div className="w-1000 h-1000 absolute -ml-10 bg-black z-10">
          <div className="w-1000 h-1000 absolute"></div>
        </div>
      </main>
    </div>
  );
}
