import Head from "next/head";
import Hero from "@/components/hero/Hero";

export default function Home({}) {
  return (
    <div className="h-full w-full mx-auto">
      <Head>
        <title>ポートフォリオサイト</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
    </div>
  );
}
